### ISSUE TITLE
Composer 404 

### ISSUE THREAD

**Issue by thedangler** [SproutVideo/sproutvideo-php#10]
placed this in my composer 
"sproutvideo/sproutvideo": "1.0.3"
got back the following.
Problem 1
    - The requested package sproutvideo/sproutvideo could not be found in any version, there may be a typo in the package name.

I am using it with laravel, but it shouldn't be an issue for composer to install it.

**Comment by podman** [comment]
It should be there: https://packagist.org/packages/sproutvideo/sproutvideo

Perhaps it was a temporary issue with composer?

Are you still having problems?

**Comment by thedangler** [comment]
Must have been, its working now.

**Comment by podman** [comment]
Glad it's working now! Marking this as closed.
