### ISSUE TITLE
Error when using uploading large file

### ISSUE THREAD

**Issue by Yahkal** [SproutVideo/sproutvideo-php#13]
I am constantly getting a error while trying to upload a large file. Using the example here is the error:
Warning: rename(,/MVI_0530.MP4): No such file or directory in /home/tvdanceorders/public_html/upload.php on line 15

Fatal error: Uncaught exception 'Exception' with message 'couldn't open file "/MVI_0530.MP4"' in /home/tvdanceorders/public_html/lib/SproutVideo/CurlClient.php:58 Stack trace: #0 /home/tvdanceorders/public_html/lib/SproutVideo/CurlClient.php(90): SproutVideo\CurlClient->request('POST', 'videos', Array, NULL, true) #1 /home/tvdanceorders/public_html/lib/SproutVideo/Resource.php(48): SproutVideo\CurlClient->upload('videos', Array, NULL, 'POST') #2 /home/tvdanceorders/public_html/lib/SproutVideo/Video.php(17): SproutVideo\Resource::upload('videos', '/MVI_0530.MP4', NULL, NULL) #3 /home/tvdanceorders/public_html/upload.php(17): SproutVideo\Video::create_video('/MVI_0530.MP4') #4 {main} thrown in /home/tvdanceorders/public_html/lib/SproutVideo/CurlClient.php on line 58

Here is the code:
		$dir = dirname($_FILES["file"]["tmp_name"]);
	$destination = $dir . '/' . $_FILES["file"]["name"];
	$des = rename($_FILES["file"]["tmp_name"], $destination);
	
SproutVideo\Video::create_video($des);

**Comment by podman** [comment]
The issue is with your renaming of the file, not the SproutVideo API client.

> Warning: rename(,/MVI_0530.MP4): No such file or directory in /home/tvdanceorders/public_html/upload.php

Here is the documentation for renaming files using PHP: http://php.net/manual/en/function.rename.php

Here is some documentation about dealing with file uploads with PHP: http://php.net/manual/en/features.file-upload.post-method.php

You probably want to use `move_uploaded_file`, not `rename`.

**Comment by Yahkal** [comment]
`rename` Was in the Sprout Video PHP API Client Example
