### ISSUE TITLE
Update the dependency on Guzzle

### ISSUE THREAD

**Issue by SvenRtbg** [SproutVideo/sproutvideo-php#7]
Depending on Guzzle 3.7.*@ dev uses an OUTDATED version of Guzzle 3.

The easiest update would be to require ^3.9.3, without development versions. This will install a maintained version of Guzzle until the end of live of Guzzle 3 is reached (announced to take place some time in 2015).

Best way would be to update to using Guzzle 5.

**Comment by podman** [comment]
We've removed the dependency on Guzzle altogether. Sorry for the delay!
