### ISSUE TITLE
I can´t list videos because of the new curl client

### ISSUE THREAD

**Issue by SergioEnrique** [SproutVideo/sproutvideo-php#8]
I´m trying to list my videos but I get an error (undefined variable: body):

![screen shot 2015-12-21 at 03 00 46](https://cloud.githubusercontent.com/assets/2131376/11927045/20e8c1da-a78f-11e5-92b3-1be00cfbc8ae.png)

This is my code (it worked fine before the composer update)
$videos = \SproutVideo\Video::list_videos(array('per_page' => 100));

**Comment by podman** [comment]
Thanks for pointing this out @SergioEnrique. This should be fixed in 4e0f4920cbc0bd10affdc5879326e6489a7c5263. Try v1.0.2.
